parameters:
#    duomenys_core.example.class: Duomenys\CoreBundle\Example

services:
#    duomenys_core.example:
#        class: %duomenys_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
